function iladata = import_adc_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ILADATA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  ILADATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  iladata = importfile("/home/hossein/projects/fz3/matlab/adc_data_analysis/iladata.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Sep-2021 21:09:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SampleinBuffer", "SampleinWindow", "TRIGGER", "design_1_isensor_sssensor_system_ilaU0probe0_1110", "design_1_isensor_sssensor_system_ilaU0probe1_1"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
iladata = readtable(filename, opts);

end