%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/hossein/projects/fz3/matlab/iladata.csv
%
% Auto-generated by MATLAB on 27-Aug-2022 11:14:15

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SampleInBuffer", "SampleInWindow", "TRIGGER", "design_1_isensor_sssensor_ilainstprobe0_130", "design_1_isensor_sssensor_ilainstprobe1_130", "design_1_isensor_sssensor_ilainstprobe2_1110", "design_1_isensor_sssensor_ilainstprobe3_1110", "design_1_isensor_sssensor_ilainstprobe4_190", "design_1_isensor_sssensor_ilainstprobe5_1", "design_1_isensor_sssensor_ilainstprobe6_1310", "design_1_isensor_sssensor_ilainstprobe7_1", "design_1_isensor_sssensor_ilainstnet_slot_0_axis_tdata310", "design_1_isensor_sssensor_ilainstnet_slot_0_axis_tvalid", "design_1_isensor_sssensor_ilainstnet_slot_0_axis_tready", "design_1_isensor_sssensor_ilainstnet_slot_0_axis_tlast", "Interface_i2s0_sensor_data_acquisition_data20", "T_Channel_i2s0_sensor_data_acquisition_data20"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Interface_i2s0_sensor_data_acquisition_data20", "T_Channel_i2s0_sensor_data_acquisition_data20"], "EmptyFieldRule", "auto");

% Import the data
iladata = readtable("/home/hossein/projects/fz3/matlab/iladata.csv", opts);


%% Clear temporary variables
clear opts

%% 

sensor_data = iladata.design_1_isensor_sssensor_ilainstprobe3_1110(115:115+1023);
sensor_data(1024) = sensor_data(1023); 
y2 = sensor_data.*sensor_data;
c = sum(y2);
d = sum((0:1023)'.*y2);
s = d/c;


